name: vic3-tiger-check
# permissions: read-all
on:
  pull_request:
    branches:
      - Imperia-Core
    types:
      - synchronize
      - opened

# on:
#     push:
#       branches-ignore:
#         - Imperia-Core

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    # Checkout the current repository (default branch)
    - name: Checkout current repository
      uses: actions/checkout@v4

    # Clone the Rust program repository from its "main" branch
    - name: Clone Rust program repository
      run: git clone --branch main https://github.com/amtep/ck3-tiger vic3-tiger

    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        # required
        app-id: ${{ secrets.BUGHUNT_BOT_ID }}
        private-key: ${{ secrets.BUGHUNT_BOT_TOKEN }}
        owner: ${{ github.repository_owner }}
    
    - name: Checkout vanilla game data repository
      uses: actions/checkout@v4
      with:
        repository: Imperia-Development-Victoria-3/Vanilla
        ref: main
        path: vanilla-game
        token: ${{ steps.app-token.outputs.token }}  # GitHub token for authentication

    # Navigate to the Rust program repository and build it
    - name: Build Rust program
      run: |
        cd vic3-tiger
        cargo build --release -p vic3-tiger
        cargo run --release -p vic3-tiger "${{ github.workspace }}" --game "${{ github.workspace }}/vanilla-game" > error.log

    - name: Check if error log is empty
      id: check_error_log
      run: |
          set +e
          if [ -s ./error.log ]; then
            echo "has_errors=true" >> $GITHUB_OUTPUT
          else
            echo "has_errors=false" >> $GITHUB_OUTPUT
          fi
          set -e

    - name: Fail PR if there are errors
      if: steps.check_error_log.outputs.has_errors == 'true' && github.event.pull_request.head.ref != 'override-branch'
      run: exit 1

