name: vic3-tiger-check
# permissions: read-all
# on:
#   pull_request:
#     branches:
#       - Imperia-Core
#     types:
#       - synchronize
#       - opened

on:
    push:
      branches-ignore:
        - Imperia-Core

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    # Checkout the current repository (default branch)
    - name: Checkout current repository
      uses: actions/checkout@v4

    # Clone the Rust program repository from its "main" branch
    - name: Clone Rust program repository
      run: git clone --branch main https://github.com/amtep/ck3-tiger vic3-tiger

    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        # required
        app-id: ${{ secrets.BUGHUNT_BOT_ID }}
        private-key: ${{ secrets.BUGHUNT_BOT_TOKEN }}
        owner: ${{ github.repository_owner }}
    
    - name: Checkout vanilla game data repository
      uses: actions/checkout@v4
      with:
        repository: Imperia-Development-Victoria-3/External-mods
        ref: vanilla
        path: vanilla-game
        token: ${{ steps.app-token.outputs.token }}  # GitHub token for authentication

    # Install Rust (using rustup)
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    # Navigate to the Rust program repository and build it
    - name: Build Rust program
      run: |
        cd vic3-tiger
        cargo build --release

    # Run the resulting executable
    - name: Run the Rust program executable
      run: |
        ./rust-program/target/release/vic-3-tiger